initial array functionality attempt for positionReader ws
BloomGameStudio/PlayerService pull request #102
Opened 2023-09-20 03:01 UTC by ghjor

Pr for ease of comm @Balugrizzly

2023-09-24 01:44 UTC, ghjor commented
Not tested for player ws, can't seem to get the example in the README to work. Successful for other ws's

2023-09-24 12:00 UTC, Balugrizzly commented
Can you elaborate on the first two sentences? More Info would be noice 
How do you know it does not work if you have not tested it?

2023-09-24 12:10 UTC, Balugrizzly requested changes
Comments from the positionreader file apply to the related other files

2023-09-24 12:10 UTC, Balugrizzly commented on controllers/ws/position/positionReader.go
> +
What is this?

2023-09-24 12:10 UTC, Balugrizzly commented on controllers/ws/position/positionReader.go
> +        c.Logger().Debugf("positionModel: %+v", positionModel)
Are you logging a empty Struct?

2023-09-24 12:10 UTC, Balugrizzly commented on controllers/ws/position/positionReader.go
> +        }
Fmting?

2023-09-24 12:10 UTC, Balugrizzly commented on controllers/ws/state/stateReader.go
This was unimplemented sortoff 
and is crossing paths with @Sarahtonein 
whats the status here?

2023-09-24 17:05 UTC, ghjor commented
> Can you elaborate on the first two sentences? More Info would be noice How do you know it does not work if you have not tested it?

Basically I couldn't get the player ws functional even without my array implementation. Sending data to the other ws's worked when I copied and pasted the readme example but I couldn't get any response when I sent to player, it just hangs. So I'm considering my array implementation untested for player ws. Somewhat semantics I think but definitely could have been clearer.

2023-09-24 17:07 UTC, ghjor commented on controllers/ws/position/positionReader.go
> +
Something I forgot to remove from when I was trying out variable JSON structures implementation, my bad.

2023-09-24 17:12 UTC, ghjor commented on controllers/ws/position/positionReader.go
> +        c.Logger().Debugf("positionModel: %+v", positionModel)
Removed

2023-09-24 17:14 UTC, ghjor commented on controllers/ws/position/positionReader.go
> +        }
Yeah not sure what happened there. Usually I have autoformat on save

2023-09-25 11:37 UTC, Balugrizzly commented
Lets go over this in vc hit me up when you are around 

> > Can you elaborate on the first two sentences? More Info would be noice How do you know it does not work if you have not tested it?
> 
> Basically I couldn't get the player ws functional even without my array implementation. Sending data to the other ws's worked when I copied and pasted the readme example but I couldn't get any response when I sent to player, it just hangs. So I'm considering my array implementation untested for player ws. Somewhat semantics I think but definitely could have been clearer.

2023-09-25 11:37 UTC, Balugrizzly commented on controllers/ws/state/stateReader.go
What happened here?

2023-09-25 11:38 UTC, Balugrizzly commented on controllers/ws/state/stateReader.go
> What happened here?

Why did you change this and what did you change?

2023-09-25 11:39 UTC, Balugrizzly commented
As for the stateReader 
Why did you change this and what did you change? 
Talking about the change after the comment on it

2023-09-29 02:19 UTC, ghjor commented on controllers/ws/state/stateReader.go
Reverted stateReader to its original state. Will save array implementation for when it's functional

2023-09-29 10:56 UTC, Balugrizzly commented
Does this make it ready for merge in your eyes? @ghjor

2023-09-29 10:57 UTC, Balugrizzly commented
Last commit looks good

2023-09-30 11:40 UTC, merged