delete player
BloomGameStudio/PlayerService pull request #122
Opened 2023-10-17 03:34 UTC by Sarahtonein

Created delete player endpoint, opening pr change

2023-10-18 10:14 UTC, Balugrizzly requested changes
You forgot:
- Changelog

And the Documentation is not 100% accurate just FYI but thats minor and up to you if you want to address that

2023-10-18 10:14 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
Not mandatory and could be smthing for later but would be nice to have 

- Name, UserID support

2023-10-18 23:31 UTC, Sarahtonein commented on controllers/rest/player/DeletePlayer.go
> Not mandatory and could be smthing for later but would be nice to have
> 
> * Name, UserID support

I have added Name and UserID, using query params for all three options (ID, Name, UserID)

2023-10-19 00:02 UTC, Sarahtonein commented
> You forgot:
> 
> * Changelog
> 
> And the Documentation is not 100% accurate just FYI but thats minor and up to you if you want to address that

Documentation has been amended to address changes.

2023-10-19 11:25 UTC, Balugrizzly requested changes
Apart from the Minor points looks good and can be merged after those changes

2023-10-19 11:25 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
You could have used a single path param and bound that into a interface or a generic.
Which is often also directly supported downstream by like gorm or whatever 
just FYI

2023-10-19 11:25 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
> +            c.Logger().Error("Invalid 'id' parameter value. Use a valid numeric ID.")
This allows Log fludding and ddosing behaviour 
consider changing it to a debug function or removing it entirly

2023-10-19 11:25 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
> +            c.Logger().Error("Invalid 'userid' parameter value. Use a valid UUID.")
Same as above

2023-10-23 05:13 UTC, Sarahtonein commented on controllers/rest/player/DeletePlayer.go
> You could have used a single path param and bound that into a interface or a generic. Which is often also directly supported downstream by like gorm or whatever just FYI


I gave this a go but not sure if this has overcomplicated things.

2023-10-23 11:26 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
This is absolutely not what i meant :)

2023-10-23 11:28 UTC, Balugrizzly requested changes
Please revise

2023-10-24 04:02 UTC, Sarahtonein commented on controllers/rest/player/DeletePlayer.go
> +            c.Logger().Error("Invalid 'id' parameter value. Use a valid numeric ID.")
> This allows Log fludding and ddosing behaviour consider changing it to a debug function or removing it entirly

I am not so sure I have resolved this with current changes, I feel like we also need to also implement things such as rate limiting if we want to reduce DDOS like behavior

2023-10-24 04:02 UTC, Sarahtonein commented
> Please revise

Revision has been done, to be discussed :)

2023-10-26 10:58 UTC, Balugrizzly reviewed
What are you doing?
I think you are going way of path here

2023-10-26 10:58 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
What are you doing?
I think you are going way of path here

2023-10-26 11:01 UTC, Balugrizzly commented
Lets talk about all this in voice

2023-10-30 11:00 UTC, Balugrizzly reviewed
Looks Good 
There is the one comment i left.
Up to you if you want to change or merge it like this

2023-10-30 11:00 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
> +    }
You do not need this.
You can set the values in the query player e.g

2023-10-30 23:30 UTC, Sarahtonein commented on controllers/rest/player/DeletePlayer.go
> +    }
> You do not need this. You can set the values in the query player e.g

I've done this through queryPlayer instead and tested. If all good I will update the README/Changelog if applicable.

2023-11-01 11:05 UTC, Balugrizzly commented on README.md
> +`DELETE /player{identifier}`
you forgot the / and its usually /:id

2023-11-01 11:11 UTC, Balugrizzly reviewed
Apart from the tiny missing / if you say this is ready i will merge

2023-11-01 11:15 UTC, Balugrizzly commented on controllers/rest/player/DeletePlayer.go
> +    }
not 100% what i meant but all good :) 
please update readme and changelog and let me know when its ready

2023-11-02 00:15 UTC, Sarahtonein commented
> Apart from the tiny missing / if you say this is ready i will merge

This has been updated :)

2023-11-02 11:20 UTC, Balugrizzly approved these changes
This Looks good

2023-11-02 11:26 UTC, merged