State ws
BloomGameStudio/PlayerService pull request #127
Opened 2023-11-09 02:30 UTC by Sarahtonein

**Example:**

**Sent to playerservice:**

```
[
{
	"ID": 5,
	"stateID": 67,
	"value": 0.73
},
{
		"ID": 6,
		"stateID": 70,
		"value": 0.11
	}
]
```

**Received from playerservice:**

```
[
	{
		"ID": 5,
		"CreatedAt": "2023-11-06T03:35:24.467926031Z",
		"UpdatedAt": "2023-11-09T02:28:18.293881202Z",
		"DeletedAt": null,
		"PlayerID": 9,
		"stateID": 67,
		"value": 0.73
	},
	{
		"ID": 6,
		"CreatedAt": "2023-11-06T03:37:31.050496586Z",
		"UpdatedAt": "2023-11-09T02:28:18.340899983Z",
		"DeletedAt": null,
		"PlayerID": 10,
		"stateID": 70,
		"value": 0.11
	}
]
```

**Related Issue:**

https://github.com/BloomGameStudio/PlayerService/issues/67

2023-11-09 12:03 UTC, Balugrizzly requested changes
Consider Using the ErrorHandler Functions

Can you Trim down the log Statements ?

2023-11-09 12:03 UTC, Balugrizzly commented on handlers/state.go
Why does this use an Array function signature?
All other handlers don't

2023-11-09 23:27 UTC, Sarahtonein commented on handlers/state.go
> Why does this use an Array function signature? All other handlers don't

I thought we were taking in an array of states for some reason. Can change this easily if that is not the case.

2023-11-10 01:41 UTC, Sarahtonein commented on controllers/ws/state/stateWriter.go
> +							return
> Consider Using the new ErrorHandlers for this

Added :)

2023-11-10 10:53 UTC, Balugrizzly commented on handlers/state.go
Not in the handlers

2023-11-10 10:54 UTC, Balugrizzly reviewed
Looks good 
lmk when you are ready for merge

2023-11-12 23:45 UTC, Sarahtonein commented on handlers/state.go
> Why does this use an Array function signature? All other handlers don't

Have removed this, tested and getting same results listed in my initial PR comments :)

2023-11-13 00:04 UTC, Sarahtonein commented
> Looks good lmk when you are ready for merge

Looks good to merge now if you are happy with changes :)

2023-11-13 12:07 UTC, Balugrizzly reviewed
Can you trim Logging?

2023-11-13 12:08 UTC, Balugrizzly commented
Can you fix merge conflicts?

2023-11-14 01:34 UTC, Sarahtonein commented
> Can you fix merge conflicts?

Merge conflicts resolved and logs trimmed

2023-11-17 11:41 UTC, Balugrizzly approved these changes
A

2023-11-17 11:43 UTC, merged