Return players if no param
BloomGameStudio/PlayerService pull request #84
Opened 2023-09-12 02:18 UTC by Sarahtonein

@Balugrizzly  can you please review this and https://github.com/BloomGameStudio/PlayerService/pull/63

2023-09-12 10:04 UTC, Balugrizzly requested changes

2023-09-12 10:04 UTC, Balugrizzly commented on controllers/rest/player/GetPlayer.go
> +	activeParam := c.QueryParam("include_active")
Why did you override my change?
can you revert that?

2023-09-12 10:04 UTC, Balugrizzly commented on controllers/rest/player/GetPlayer.go
> +	if err := db.Preload(clause.Associations).Where("active = ?", queryPlayer.Active).Find(players).Error; err != nil {
Why is a prepared string statement needed here?

can you use typed where clause

cant you filter by queryPlayer like i did initially?

2023-09-13 00:52 UTC, Sarahtonein commented on controllers/rest/player/GetPlayer.go
> +	activeParam := c.QueryParam("include_active")
Yes will revert, changed it as I thought we were going to use include_active.

2023-09-13 01:12 UTC, Sarahtonein commented on controllers/rest/player/GetPlayer.go
> +	if err := db.Preload(clause.Associations).Where("active = ?", queryPlayer.Active).Find(players).Error; err != nil {
I tried to filter using this line and was receiving an empty slice:

```if err := db.Preload(clause.Associations).Where(queryPlayer.Active).Find(players).Error; err != nil {
``` 

Does it work on your end?

2023-09-13 10:01 UTC, Balugrizzly commented on controllers/rest/player/GetPlayer.go
> +	if err := db.Preload(clause.Associations).Where("active = ?", queryPlayer.Active).Find(players).Error; err != nil {
Mate this line is empty for me 

My line that was there initially worked for me yes 
You added the `.Active` having that alone i can see as not working

2023-09-14 05:43 UTC, Sarahtonein commented on controllers/rest/player/GetPlayer.go
> +	if err := db.Preload(clause.Associations).Where("active = ?", queryPlayer.Active).Find(players).Error; err != nil {
> Mate this line is empty for me
> 
> My line that was there initially worked for me yes You added the `.Active` having that alone i can see as not working

Edited my response, the code I put in my prior comment was on the same line as the backticks :( 

I have updated per your response :)

2023-09-14 12:35 UTC, Balugrizzly commented on controllers/rest/player/GetPlayer.go
> +	if err := db.Preload(clause.Associations).Where("active = ?", queryPlayer.Active).Find(players).Error; err != nil {
Yea was never saying this was not working.
You sent me a blank line and asked if it was working i understood it that it does not work on your end.
I in response to that said i could see the possibility that the .Active is the cause of it. And told you that i know that my line that was there initially is known to work.
 
The issue was the non typed string query.

but kk all good :) good work

2023-09-14 12:37 UTC, merged