Feature crud update
BloomGameStudio/PlayerService pull request #90
Opened 2023-09-15 04:32 UTC by Sarahtonein

2023-09-15 16:54 UTC, Balugrizzly reviewed
What is your plan with the update process 
specific to the data handling and binding?

2023-09-15 16:54 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
> +	}{}
Why are you not using the public model here?

2023-09-15 16:54 UTC, Balugrizzly commented
But apart from the above section looks good

2023-10-18 03:56 UTC, Sarahtonein commented on controllers/rest/player/UpdatePlayer.go
> +	}{}
> Why are you not using the public model here?

I was having a problem with using the model so opted for a new struct. I have modified this now.

2023-10-18 10:29 UTC, Balugrizzly requested changes

2023-10-18 10:29 UTC, Balugrizzly commented on README.md
> +
Why are you using "PUT" 

The below sentence is in direct contradiction with the HTTP method

2023-10-18 10:29 UTC, Balugrizzly commented on README.md
> +http://127.0.0.1:1323/1
Wrong URL and path?

2023-10-18 10:29 UTC, Balugrizzly commented on README.md
> +}
Invalid/Incomplete Json?

2023-10-18 10:29 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
optional:
errors and error codes  are not documented

2023-10-18 10:30 UTC, Balugrizzly commented
Can you fix Merge conflicts?

2023-10-19 01:22 UTC, Sarahtonein commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Transform.Scale = updateData.Transform.Scale
> Why are you only updating those three selected fields and no others? Also does that work without handling the associated ID's?

Will add the other fields. And yes able to update the position and rotation for example without providing an ID for the position and rotation, please see below example:

![image](https://github.com/BloomGameStudio/PlayerService/assets/109805833/e256e5a3-4fa3-4766-95c2-092d6034aee2)

2023-10-19 01:25 UTC, Sarahtonein commented on README.md
> +
> Why are you using "PUT"
> 
> The below sentence is in direct contradiction with the HTTP method

Considering that PUT 'resets' unspecified fields I suppose we should be using PATCH HTTP method instead?

2023-10-19 11:08 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Transform.Scale = updateData.Transform.Scale
Okey

2023-10-19 11:09 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Transform.Scale = updateData.Transform.Scale
let me know when you have added all the fields.
I will then resolve this convo

2023-10-19 11:11 UTC, Balugrizzly commented on README.md
> +
Yes 
Will assume you made/make the necessary changes and makr this as resolved

2023-10-19 11:17 UTC, Balugrizzly requested changes

2023-10-19 11:17 UTC, Balugrizzly commented on README.md
Ähm why did you remove the entire Updateplayer section?

2023-10-19 11:17 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Active = updateData.Active
I highly suspect updating the active field wont work.
Look into updating false and null values

2023-10-19 11:17 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
> +
What is this?

2023-10-26 02:27 UTC, Sarahtonein commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Transform.Scale = updateData.Transform.Scale
> let me know when you have added all the fields. I will then resolve this convo

Other fields have been added.

2023-10-26 11:06 UTC, Balugrizzly commented
Are you planing to discuss this in Voice?
Asking as there are many open points after your revision

2023-10-27 07:24 UTC, Sarahtonein commented
> Are you planing to discuss this in Voice? Asking as there are many open points after your revision

Yes, wanting to go over this in voice please.

2023-10-27 10:02 UTC, Balugrizzly commented
Alright

2023-10-30 05:24 UTC, Sarahtonein commented on controllers/rest/player/UpdatePlayer.go
GoFMT setup :)

2023-10-30 05:44 UTC, Sarahtonein commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Active = updateData.Active
> I highly suspect updating the active field wont work. Look into updating false and null values

Updating active field like this does work, I had a look into updating false and null values and it took me down the discussed pointer hole.

2023-10-30 05:47 UTC, Sarahtonein commented on controllers/rest/player/UpdatePlayer.go
> Optional
> 
> Support for Name and UserId

Added and will be modifying here depending on how this is structured in DELETE requests.

2023-10-30 11:06 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Active = updateData.Active
Are you 100% sure? Have you tested this?
Do you wanna bet? :)

2023-10-31 00:05 UTC, Sarahtonein commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Active = updateData.Active
I did the following:

1. Created a player
```
{
	"ID": 19,
	"CreatedAt": "2023-10-30T23:59:14.416803326Z",
	"UpdatedAt": "2023-10-30T23:59:14.416803326Z",
	"DeletedAt": null,
	"UserID": "25f90f11-0306-462b-8781-04d8b47234e8",
	"name": "test_player",
	"layer": "",
	"ens": "",
	"active": true,
	"transform": {
		"RotationID": 83,
		"ScaleID": 83,
		"PositionID": 83,
		"position": {
			"ID": 83,
			"CreatedAt": "2023-10-30T23:59:14.40569386Z",
			"UpdatedAt": "2023-10-30T23:59:14.40569386Z",
			"DeletedAt": null,
			"x": 1,
			"y": 2,
			"z": 3
		},
		"rotation": {
			"ID": 83,
			"CreatedAt": "2023-10-30T23:59:14.411727103Z",
			"UpdatedAt": "2023-10-30T23:59:14.411727103Z",
			"DeletedAt": null,
			"x": 4,
			"y": 5,
			"z": 6,
			"w": 0
		},
		"scale": {
			"ID": 83,
			"CreatedAt": "2023-10-30T23:59:14.414415062Z",
			"UpdatedAt": "2023-10-30T23:59:14.414415062Z",
			"DeletedAt": null,
			"x": 7,
			"y": 8,
			"z": 9
		}
	},
	"states": null,
	"level": {
		"ID": 0,
		"CreatedAt": "0001-01-01T00:00:00Z",
		"UpdatedAt": "0001-01-01T00:00:00Z",
		"DeletedAt": null,
		"PlayerID": 0,
		"levelID": 0
	}
}
```

2. Set active to false
request body
```
{
  "UserID": "25f90f11-0306-462b-8781-04d8b47234e8",
  "Name": "test_player",
  "Layer": "layer1",
  "Ens": "",
	"Active": false,
  "Transform": {
    "Position": {
      "x": 1,
      "y": 2,
      "z": 3
    },
    "Rotation": {
      "x": 4,
      "y": 5,
      "z": 6
    },
    "Scale": {
      "x": 7,
      "y": 8,
      "z": 9
    }
  },
  "states": [
    {
      "id": 1,
      "value": 0.4
    },
    {
      "id": 2,
      "value": 0.1
    }
  ]
}
```

Response, and debug log from player service:

```
{
	"ID": 19,
	"CreatedAt": "2023-10-30T23:59:14.416803326Z",
	"UpdatedAt": "2023-10-31T00:01:27.077767629Z",
	"DeletedAt": null,
	"UserID": "25f90f11-0306-462b-8781-04d8b47234e8",
	"name": "test_player",
	"layer": "layer1",
	"ens": "",
	"active": false,
	"transform": {
		"RotationID": 84,
		"ScaleID": 84,
		"PositionID": 84,
		"position": {
			"ID": 84,
			"CreatedAt": "2023-10-31T00:01:27.070353261Z",
			"UpdatedAt": "2023-10-31T00:01:27.070353261Z",
			"DeletedAt": null,
			"x": 1,
			"y": 2,
			"z": 3
		},
		"rotation": {
			"ID": 84,
			"CreatedAt": "2023-10-31T00:01:27.073501709Z",
			"UpdatedAt": "2023-10-31T00:01:27.073501709Z",
			"DeletedAt": null,
			"x": 4,
			"y": 5,
			"z": 6,
			"w": 0
		},
		"scale": {
			"ID": 84,
			"CreatedAt": "2023-10-31T00:01:27.075746786Z",
			"UpdatedAt": "2023-10-31T00:01:27.075746786Z",
			"DeletedAt": null,
			"x": 7,
			"y": 8,
			"z": 9
		}
	},
	"states": [
		{
			"ID": 89,
			"CreatedAt": "2023-10-31T00:01:27.081366954Z",
			"UpdatedAt": "2023-10-31T00:01:27.081366954Z",
			"DeletedAt": null,
			"PlayerID": 19,
			"stateID": 0,
			"value": 0.4
		},
		{
			"ID": 90,
			"CreatedAt": "2023-10-31T00:01:27.081366954Z",
			"UpdatedAt": "2023-10-31T00:01:27.081366954Z",
			"DeletedAt": null,
			"PlayerID": 19,
			"stateID": 0,
			"value": 0.1
		}
	],
	"level": {
		"ID": 0,
		"CreatedAt": "0001-01-01T00:00:00Z",
		"UpdatedAt": "0001-01-01T00:00:00Z",
		"DeletedAt": null,
		"PlayerID": 0,
		"levelID": 0
	}
}
```
``
playerservice-playerservice-1  | {"time":"2023-10-31T00:01:27.070014479Z","level":"DEBUG","prefix":"echo","file":"UpdatePlayer.go","line":"47","message":"Player Active status before update:true"}
```` 
3. Stop player service

4. Start player service again

5. Set player to active

request body
```
{
  "UserID": "25f90f11-0306-462b-8781-04d8b47234e8",
  "Name": "test_player",
  "Layer": "layer1",
  "Ens": "",
	"Active": true,
  "Transform": {
    "Position": {
      "x": 1,
      "y": 2,
      "z": 3
    },
    "Rotation": {
      "x": 4,
      "y": 5,
      "z": 6
    },
    "Scale": {
      "x": 7,
      "y": 8,
      "z": 9
    }
  },
  "states": [
    {
      "id": 1,
      "value": 0.4
    },
    {
      "id": 2,
      "value": 0.1
    }
  ]
}

```
Response, and debug log from player service:

```
playerservice-playerservice-1  | {"time":"2023-10-31T00:02:29.567010124Z","level":"DEBUG","prefix":"echo","file":"UpdatePlayer.go","line":"47","message":"Player Active status before update:false"}
```

```
{
	"ID": 19,
	"CreatedAt": "2023-10-30T23:59:14.416803326Z",
	"UpdatedAt": "2023-10-31T00:02:29.575995316Z",
	"DeletedAt": null,
	"UserID": "25f90f11-0306-462b-8781-04d8b47234e8",
	"name": "test_player",
	"layer": "layer1",
	"ens": "",
	"active": true,
	"transform": {
		"RotationID": 85,
		"ScaleID": 85,
		"PositionID": 85,
		"position": {
			"ID": 85,
			"CreatedAt": "2023-10-31T00:02:29.567668357Z",
			"UpdatedAt": "2023-10-31T00:02:29.567668357Z",
			"DeletedAt": null,
			"x": 1,
			"y": 2,
			"z": 3
		},
		"rotation": {
			"ID": 85,
			"CreatedAt": "2023-10-31T00:02:29.570841487Z",
			"UpdatedAt": "2023-10-31T00:02:29.570841487Z",
			"DeletedAt": null,
			"x": 4,
			"y": 5,
			"z": 6,
			"w": 0
		},
		"scale": {
			"ID": 85,
			"CreatedAt": "2023-10-31T00:02:29.573016994Z",
			"UpdatedAt": "2023-10-31T00:02:29.573016994Z",
			"DeletedAt": null,
			"x": 7,
			"y": 8,
			"z": 9
		}
	},
	"states": [
		{
			"ID": 91,
			"CreatedAt": "2023-10-31T00:02:29.580191435Z",
			"UpdatedAt": "2023-10-31T00:02:29.580191435Z",
			"DeletedAt": null,
			"PlayerID": 19,
			"stateID": 0,
			"value": 0.4
		},
		{
			"ID": 92,
			"CreatedAt": "2023-10-31T00:02:29.580191435Z",
			"UpdatedAt": "2023-10-31T00:02:29.580191435Z",
			"DeletedAt": null,
			"PlayerID": 19,
			"stateID": 0,
			"value": 0.1
		}
	],
	"level": {
		"ID": 0,
		"CreatedAt": "0001-01-01T00:00:00Z",
		"UpdatedAt": "0001-01-01T00:00:00Z",
		"DeletedAt": null,
		"PlayerID": 0,
		"levelID": 0
	}
}
```

I think this covers the scenario in which you described but let me know if I''m off here. I have tested this the other way around too fwiw.

As mentioned if Active is not included in the request body it defaults to false.

2023-11-01 11:31 UTC, Balugrizzly commented on controllers/rest/player/UpdatePlayer.go
> +	queryPlayer.Active = updateData.Active
okey i believe you and that you are right 
we want the active field to be omitable

2023-11-04 10:58 UTC, Balugrizzly reviewed
This looks good apart from the tiny two comments i made.
Where are we here in generall?

2023-11-04 10:58 UTC, Balugrizzly commented on CHANGELOG.md
This is wrong.
There is no 0.3 release

2023-11-04 10:58 UTC, Balugrizzly commented on README.md
> +| ID   | INT  | YES       |
Type is inaccurate

2023-11-05 21:58 UTC, Sarahtonein commented on README.md
> +| ID   | INT  | YES       |
Amended, thanks for catching that

2023-11-05 21:58 UTC, Sarahtonein commented on CHANGELOG.md
removed 0.3

2023-11-05 22:01 UTC, Sarahtonein commented
> This looks good apart from the tiny two comments i made. Where are we here in generall?

I think this is ready to merge from my tests. 

Example below:

URL: http://localhost:1323/player/2

JSON sent to service

```
{
  "UserID": "d1813663-cf15-4f33-a0c2-2d3b1c2fead5",
  "Name": "2",
  "Layer": "layer1",
  "Ens": "",
	"active": true,
  "Transform": {
    "Position": {
      "x": 4,
      "y": 5,
      "z": 6
    },
    "Rotation": {
      "x": 7,
      "y":	75,
      "z": 6
    },
    "Scale": {
      "x": 6,
      "y": 7,
      "z": 10
    }
  },
  "states": [
    {
      "stateid": 4,
      "value": 0.69
    },
    {
      "stateid": 20,
      "value": 0.420
    }
  ]
}
```

response from service:

```
{
	"ID": 2,
	"CreatedAt": "2023-11-05T21:56:28.17432539Z",
	"UpdatedAt": "2023-11-05T21:59:50.03589367Z",
	"DeletedAt": null,
	"UserID": "d1813663-cf15-4f33-a0c2-2d3b1c2fead5",
	"name": "2",
	"layer": "layer1",
	"ens": "",
	"active": true,
	"transform": {
		"RotationID": 175,
		"ScaleID": 175,
		"PositionID": 175,
		"position": {
			"ID": 175,
			"CreatedAt": "2023-11-05T21:59:49.962610279Z",
			"UpdatedAt": "2023-11-05T21:59:49.962610279Z",
			"DeletedAt": null,
			"x": 4,
			"y": 5,
			"z": 6
		},
		"rotation": {
			"ID": 175,
			"CreatedAt": "2023-11-05T21:59:50.000698312Z",
			"UpdatedAt": "2023-11-05T21:59:50.000698312Z",
			"DeletedAt": null,
			"x": 7,
			"y": 75,
			"z": 6,
			"w": 0
		},
		"scale": {
			"ID": 175,
			"CreatedAt": "2023-11-05T21:59:50.024145978Z",
			"UpdatedAt": "2023-11-05T21:59:50.024145978Z",
			"DeletedAt": null,
			"x": 6,
			"y": 7,
			"z": 10
		}
	},
	"states": [
		{
			"ID": 9,
			"CreatedAt": "2023-11-05T21:59:50.080820909Z",
			"UpdatedAt": "2023-11-05T21:59:50.080820909Z",
			"DeletedAt": null,
			"PlayerID": 2,
			"stateID": 4,
			"value": 0.69
		},
		{
			"ID": 10,
			"CreatedAt": "2023-11-05T21:59:50.080820909Z",
			"UpdatedAt": "2023-11-05T21:59:50.080820909Z",
			"DeletedAt": null,
			"PlayerID": 2,
			"stateID": 20,
			"value": 0.42
		}
	],
	"level": {
		"ID": 0,
		"CreatedAt": "0001-01-01T00:00:00Z",
		"UpdatedAt": "0001-01-01T00:00:00Z",
		"DeletedAt": null,
		"PlayerID": 0,
		"levelID": 0
	}
}
```

Various fields are successfully updating (Active / Position / Rotation / Scale and States)

2023-11-06 11:49 UTC, Balugrizzly approved these changes
Changes Lookg good

2023-11-06 11:53 UTC, Balugrizzly commented
@Sarahtonein Will merge this but feel free to make additional addition in a new branch

2023-11-06 11:54 UTC, merged